replicaCount: 2

image:
  repository: <your-ecr-repo>/flask-app
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 5000

ingress:
  enabled: true
  hosts:
    - host: flask-app.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: flask-app-tls
      hosts:
        - flask-app.example.com